[package]
name = "mongodb-opentelemetry-receiver"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mongodb-opentelemetry-receiver"
path = "src/main.rs"

[profile.release]
lto = true
codegen-units = 1

[dependencies]
mongodb = { version = "3" }
serde = "1"
regex = "1"
lazy_static = "1"

# binary only
color-eyre = "0"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
# dialoguer = "0"
# pretty_assertions = "1"
