[workspace]
members = [
    "bin/*",
    "crates/component",
    "crates/receivers/*",
    "crates/processors/*",
    "crates/exporters/*",
]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1
