name: test
on: [push, pull_request, workflow_call]
jobs:
  package-matrix:
    uses: ./.github/workflows/package-matrix.yml
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Audit
        continue-on-error: true
        run: |
          cargo install cargo-audit
          cargo audit
  test:
    runs-on: ubuntu-latest
    needs: [package-matrix]
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJson(needs.package-matrix.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: romnn/cargo-feature-combinations@main
      - name: Test
        run: cargo fc test --package "${{ matrix.package.name }}" --all-targets
      - name: Lint
        continue-on-error: true
        run: >-
          cargo fc clippy --package "${{ matrix.package.name }}" --tests --benches --examples -- -Dclippy::all -Dclippy::pedantic
  publish:
    name: publish (dry-run)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Publish crates (dry-run)
        uses: romnn/publish-crates@main
        with:
          dry-run: true
          resolve-versions: true
